pgss15compbio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from pgss15compbio import views


urlpatterns = [
    url(r'^$', views.hello, name="hello"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^skeletonpages/', include('skeletonpages.urls')),
    url(r'^accounts/', include('userena.urls')),
    # 'django.views.static.serve',
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skeletonpages/urls.py
from django.conf.urls import url, include
from skeletonpages import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^input/$', views.input, name='input'),
  url(r'^output/$', views.output, name='output'),
  url(r'^about_us/$', views.about_us, name='about_us'),
  url(r'^instructions/$', views.instructions, name='instructions'),
  url(r'^file_test/$', views.file_test, name='file_test'),
  url(r'^simulations/(?P<simulation_id>\d+)/show', views.show_simulation, name="show_simulation"),
  url(r'^simulations/new/$', views.new_simulation, name="new_simulation"),
  url(r'^simulations/create/$', views.create_simulation, name="create_simulation"),
  url(r'^simulations/create/ajax$', views.create_simulation_ajax, name="create_simulation_ajax"),
  url(r'^simulations/(?P<simulation_id>\d+)/delete/$', views.del_simulation, name="del_simulation"),
  url(r'^keep_alive/$', views.keep_alive, name="keep_alive"),
  url(r'^simulation_running/$', views.simulation_running, name="simulation_running"),

]

skeletonpages/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.db.models.signals import post_save, post_init
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile
from time import strftime

class DemoObject(models.Model):
  object_name = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Object Name")
  object_description = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Object Description")
  object_number = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Object Number")

  def __unicode__(self):
    return "{}".format(self.object_name or self.object_description or "N/A")

def upload_path(self, filename):
  return strftime("%Y/%m/%d/%H/%M/{}".format(filename))

class AlgorithmRun(models.Model):
  # status should be "PROCESSING" or "COMPLETE"
  status = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Status")
  
  name = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Name")
  description = models.CharField(max_length = 2048, null = True, blank = True, verbose_name = "Description")
  input_file = models.FileField(upload_to = upload_path, null = True, blank = True)
  output_file = models.FileField(upload_to = upload_path, null = True, blank = True)
  input_text = models.CharField(max_length = 8192, null = True, blank = True, verbose_name = "Input Text")
  output_text = models.CharField(max_length = 32768, null = True, blank = True, verbose_name = "Output Text")
  def __unicode__(self):
    return "{}".format(self.name or "Unnamed Algorithm Run")


class UserProfile(UserenaBaseProfile):
  user = models.OneToOneField(User)

  algorithm_runs = models.ManyToManyField(AlgorithmRun, null = True, blank = True)

  organization = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Organization Name")
  scientific_field = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Field")

  def __unicode__(self):
      return "Profile information for {}".format(self.user.email)

  class Meta:
      verbose_name = "Profile"
      verbose_name_plural = "Profiles"

  def create_user_profile(sender, instance, created, **kwargs):
      if created:
          UserProfile.objects.create(user=instance)

skeletonpages/forms.py
from django import forms

class AlgorithmRunForm(forms.Form):
  input_file = forms.FileField(
    label="Select input file",
    help_text="Max 1MB",
    widget=forms.FileInput(attrs={"class":"btn btn-default"})
  )

skeletonpages/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from skeletonpages.forms import AlgorithmRunForm
from django.core.urlresolvers import reverse
from skeletonpages.models import *
from Parser import Parser
from django.core.files import File
from time import time
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from random import random
import json
import pdb
from django.utils.safestring import mark_safe
import Parser
from StringIO import StringIO
from pgss15compbio.celery import finish_iteration


def index(request):
  context = {'active_tab': '#index'}
  return render_to_response('skeletonpages/index.html', context, RequestContext(request))

def input(request):
  if request.method == 'POST':
    form = AlgorithmRunForm(request.POST, request.FILES)
    if form.is_valid():
      out_file = File(open("./pgss15compbio/media/out_file.csv", "w+"))
      p = Parser()
      model = p.get_model(request.FILES['input_file'], out_file)
      model.iterate()
      new_algorithm_run = AlgorithmRun(input_file=request.FILES['input_file'],
        output_file=out_file)
      new_algorithm_run.save()
      # Redirect to the document list after POST
      h = HttpResponseRedirect("../../media/out_file.csv")
      return h
  else:
    form = AlgorithmRunForm() # A empty, unbound form
  
  context = {'active_tab': '#input-nav', 'form': form}
  return render_to_response('skeletonpages/input.html', context, RequestContext(request))

def output(request):
  context = {'active_tab': '#output-nav'}
  return render_to_response('skeletonpages/output.html', context, RequestContext(request))

def instructions(request):
  context = {'active_tab': '#instructions-nav'}
  return render_to_response('skeletonpages/instructions.html', context, RequestContext(request))

def about_us(request):
  context = {'active_tab': '#about_us-nav'}
  return render_to_response('skeletonpages/about_us.html', context, RequestContext(request))

def del_simulation(request, simulation_id):
  simulation = AlgorithmRun.objects.get(pk = simulation_id)
  simulation.delete()
  return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def show_simulation(request, simulation_id):
  simulation = AlgorithmRun.objects.get(pk = simulation_id)

  output_file = simulation.output_file
  first_line = output_file.readline()

  list_of_lists = []
  for variable_name in first_line.strip().split(","):
    list_of_lists.append([variable_name])

  for line in output_file.readlines():
    # ipdb.set_trace()
    split_line = line.split(",")
    for index, value in enumerate(split_line):
      list_of_lists[index].append(float(value.rstrip()))

  dictionary = {}
  for sublist in list_of_lists:
    dictionary.update( { sublist[0]: sublist[1:] } )

  keys = []
  for sublist in list_of_lists:
    keys.append(sublist[0])

  context = {'simulation': simulation, 'simulation_values': mark_safe(dictionary), 'variable_names': keys}

  return render_to_response('skeletonpages/show_simulation.html', context, RequestContext(request))

def new_simulation(request):
  form = AlgorithmRunForm()
  return render_to_response('skeletonpages/new_simulation.html', 
                            {'form': form}, 
                            context_instance = RequestContext(request))

def keep_alive(request):
  return HttpResponse("1");

def create_simulation_ajax(request):
  if request.GET:
    try:
      in_file = File(open("./pgss15compbio/media/temp.txt", "w+"))
      in_file.write(request.GET['str'])
      Parser.Parser().get_model(in_file, 'hello')
      return HttpResponse("1")
    except ValueError:
      return HttpResponse(status=412)
  print request.POST
  form = AlgorithmRunForm(request.POST, request.FILES)
  if form.is_valid():
    new_algorithm_run = AlgorithmRun(input_file = request.FILES['input_file'],
      name = request.POST['name'], description = request.POST['description'], 
      status = "PROCESSING" )

    new_algorithm_run.save()
    request.user.userprofile.algorithm_runs.add(new_algorithm_run)
    request.user.userprofile.save()

    finish_iteration.delay(new_algorithm_run.pk)

    context = {'simulation': new_algorithm_run}

    return render_to_response('skeletonpages/simulation_running.html', context, RequestContext(request))

def simulation_running(request):
  context = {'simulation': 5}

  return render_to_response('skeletonpages/simulation_running.html', context, RequestContext(request))


def create_simulation(request):
  form = AlgorithmRunForm(request.POST, request.FILES)
  if form.is_valid():
    file_name = "./pgss15compbio/media/out_file_{}.csv".format( str(random())[2:] )
    out_file = File(open(file_name, "w+"))
    p = Parser()
    model = p.get_model(request.FILES['input_file'], out_file)
    model.iterate()
    new_algorithm_run = AlgorithmRun(input_file = request.FILES['input_file'],
      output_file = out_file, name=request.POST['name'],
      description = request.POST['description'])

    new_algorithm_run.save()
    request.user.userprofile.algorithm_runs.add(new_algorithm_run)
    request.user.userprofile.save()

    output_file = new_algorithm_run.output_file
    first_line = output_file.readline()

    list_of_lists = []
    for variable_name in first_line.strip().split(","):
      list_of_lists.append([variable_name])

    for line in output_file.readlines():
      # ipdb.set_trace()
      split_line = line.split(",")
      for index, value in enumerate(split_line):
        list_of_lists[index].append(float(value.rstrip()))

    dictionary = {}
    for sublist in list_of_lists:
      dictionary.update( { sublist[0]: sublist[1:] } )
      
    keys = []
    for sublist in list_of_lists:
      keys.append(sublist[0])

    context = {'simulation': simulation, 'simulation_values': mark_safe(dictionary), 'variable_names': keys}


    return render_to_response('skeletonpages/show_simulation.html',
      context,
      RequestContext(request)
      )

def file_test(request):
    # Handle file upload
    if request.method == 'POST':
        form = AlgorithmRunForm(request.POST, request.FILES)
        if form.is_valid():
            out_file = File(open("./pgss15compbio/media/out_file.csv", "w+"))
            p = Parser()
            model = p.get_model(request.FILES['input_file'], out_file)
            model.iterate()
            new_algorithm_run = AlgorithmRun(input_file = request.FILES['input_file'],
              output_file=out_file)
            new_algorithm_run.save()
            # Redirect to the document list after POST
            h = HttpResponseRedirect("../../media/out_file.csv")

            return h
            
    else:
        form = AlgorithmRunForm() # A empty, unbound form

    # Load documents for the list page
    algorithm_runs = AlgorithmRun.objects.all()

    # Render list page with the documents and the form
    return render_to_response(
        'skeletonpages/file_test.html',
        {'algorithm_runs': algorithm_runs, 'form': form},
        context_instance=RequestContext(request)
    )

skeletonpages/templates/skeletonpages/2index.html
<!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/static/application.css" />
    <title>Bio</title>
  </head>
  <body>
    <div class="hello-world">Hello, world!</div>
  </body>
</html>

skeletonpages/templates/skeletonpages/about_us.html
{% include 'common/_header.html' %}

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <!-- START THE FEATURETTES -->
    <div class = "container marketing">
      <br class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">A Powerful Engine.<span class="text-muted"> It'll blow your mind.</span></h2>
          <p class="lead">Our in-house, custom engine gets accurate results. Using the Gillespie algorithm and the Lotka-Volterra model, the engine can simulate an
            infinite number of reactions, each with different initial constraints.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Database-Cloud-256.png" >
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 col-md-push-5">
            <h2 class="featurette-heading">Platform Agnostic.<span class="text-muted"> Run once, use anywhere.</span></h2>
            <p class="lead">GAUSS is a strong, independent web application that doesn't need many resources. The cloud-based platform will run your simulations, all from 
              your favorite web-connnected device.</p>
            </div>
            <div class="col-md-5 col-md-pull-7">
              <img class="featurette-image img-responsive center-block" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Coding-Html-256.png" >
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7">
              <h2 class="featurette-heading">Beautiful. <span class="text-muted"></span></h2>
              <p class="lead">GAUSS was carefully crafted with the latest Bootstrap. Our attention to detail ensures that your results come out looking their very best. Who says that computational biology can't be pretty?</p>
            </div>
            <div class="col-md-5">
              <img class="featurette-image img-responsive center-block" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Images-256.png" >
            </div>
          </div>

          <hr class="featurette-divider">

          <!-- /END THE FEATURETTES -->
        </div>
        {% include 'common/_footer.html' %}

skeletonpages/templates/skeletonpages/file_test.html
{% include 'common/_header.html' %}

<!-- List of uploaded documents -->
{% if algorithm_runs %}
    <ul>
    {% for algorithm_run in algorithm_runs %}
        {% if algorithm_run.input_file %}
            <li><a href="{{ algorithm_run.input_file.url }}">{{ algorithm_run.input_file.name }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No documents.</p>
{% endif %}

<!-- Upload form. Note enctype attribute! -->
<form action="{% url 'file_test' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
    <p>{{ form.input_file.label_tag }} {{ form.input_file.help_text }}</p>
    <p>
        {{ form.input_file.errors }}
        {{ form.input_file }}
    </p>
    <p><input type="submit" value="Upload" /></p>
</form>

{% include 'common/_footer.html' %}

skeletonpages/templates/skeletonpages/index.html
{% include 'common/_header.html' %}

<!-- Sets up jumbotron -->
<div class="jumbotron col-md-12" style="height: 350px; padding-top:75px">
	<h1 class = "jTextTop">G A U S S</h1>
	<p class="tronText">Gillespie Algorithm Used for Stochastic Simulation</p>
	<p><a class="btn btn-primary btn-lg tronText" href="/skeletonpages/simulations/new/" role="button">Get Started</a></p>
</div>

<!-- Three columns of text below the carousel -->
<div class="container marketing">
	<div class="row">
		<div class="col-lg-4">
			<img class="img-circle" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Checklist-512.png"  width="140" height="140">
			<h2>Easy</h2>
			<p>Upload constraints using a .react file.</p>
			<!--<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4">
			<img class="img-circle" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Microchip-512.png"  width="140" height="140">
			<h2>Fast</h2>
			<p>Using a custom-made Gillespie Algorithm powered engine and our Django backend, GAUSS will get your results in a snap.</p>
			<!--<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4">
			<img class="img-circle" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Analytics-512.png" alt="Analytical" width="140" height="140">
			<h2>Analytical</h2>
			<p>GAUSS utilizes plotly.js, a powerful Javascript Library for graphing. Data can be downloaded as a .csv file.</p>
			<!--<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
		</div><!-- /.col-lg-4 -->
	</div><!-- /.row -->
</div>

<div class = "container marketing" style="center">
      <br class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">A Powerful Engine.<span class="text-muted"> It'll blow your mind.</span></h2>
          <p class="lead">Our in-house, custom engine gets accurate results. Using the Gillespie algorithm and the Lotka-Volterra model, the engine can simulate an
            infinite number of reactions, each with different initial constraints.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-responsive center-block" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Database-Cloud-256.png" >
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 col-md-push-5">
            <h2 class="featurette-heading">Platform Agnostic.<span class="text-muted"> Run once, use anywhere.</span></h2>
            <p class="lead">GAUSS is a strong, independent web application that doesn't need many resources. The cloud-based platform will run your simulations, all from 
              your favorite web-connnected device.</p>
            </div>
            <div class="col-md-5 col-md-pull-7">
              <img class="featurette-image img-responsive center-block" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Coding-Html-256.png" >
            </div>
          </div>

          <hr class="featurette-divider">

          <div class="row featurette">
            <div class="col-md-7">
              <h2 class="featurette-heading">Beautiful. <span class="text-muted"></span></h2>
              <p class="lead">GAUSS was carefully crafted with the latest Bootstrap. Our attention to detail ensures that your results come out looking their very best. Who says that computational biology can't be pretty?</p>
            </div>
            <div class="col-md-5">
              <img class="featurette-image img-responsive center-block" src="https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Images-256.png" >
            </div>
          </div>

          <br>

          <!-- /END THE FEATURETTES -->
        </div>

{% include 'common/_footer.html' %}

skeletonpages/templates/skeletonpages/input.html
{% include 'common/_header.html' %}
<div class = "container input">
<div class="row" align= "center">
  <h1 id="title">Upload file</h1>

  <p></p>
  <form action="{% url 'input' %}" method="post" enctype="multipart/form-data">
  <div class="col-lg-12">
    <div class="col-lg-4 col-lg-offset-4">
    <div class = "form-group">
      {{ form.input_file }}
      <!--div class="form-group">
        <label for="id_input_file">Upload .react here</label>
        <input type="file" id="id_input_file">
      </div>
    </div--><!-- /.col-lg-6 -->
    </div>
    </div>
  </div>

  <br><br>

  <div class="row" style="padding-top: 120px;">
    <h1>Input data manually</h1>

  </div>

  <div class="row" id="body">
    <div class="col-lg-12" align="center">
      
      <div class="bodyArea">
          {% csrf_token %}
        <div class="input-group col-lg-3" align="center">
          <label>Number of Iterations:</label>
          <input type="text" class="form-control" id="num_of_iterations" placeholder="Number of Iterations" aria-describedby="basic-addon1">
        </div>

        <div class="col-lg-6">
          <label>Reagents:</label>
          <input type="text" class="form-control" id="reagent" placeholder="Reagent Name" aria-describedby="basic-addon1">
          <input type="text" class="form-control" id="reagent_concen" placeholder="Reagent Concentration" aria-describedby="basic-addon1">
        </div>
        <div class="col-lg-6">
          <label>List of Reagent Names:</label>
          <li class="list-group-item" id="reagentNamesList">List of Reagent Names</li>
          <label>List of Reagent Concentrations:</label>
          <li class="list-group-item" id="reagentConcenList">List of Reagent Concentrations</li>
        </div>
        <div id="incomplete_reagent" class="alert alert-danger" role="alert" style="display:none">
          You must fill out both Reagent Name and Reagent Concentration.
        </div>

        <div class="row col-lg-12" align="center" style="padding-top:20px;">
          <button type="button" class="btn btn-default ghost-btn" id="add_reagent">Add Reagent</button>
        </div>

        <div class="row col-lg-6">
          <label>Reactions:</label>
          <input type="text" class="form-control" id="reaction" align="center" placeholder="Reaction Formula" aria-describedby="basic-addon1">
        </div>

        <div class="col-lg-6">
          <label>List of Reactions:</label>
          <li class="list-group-item" id="reactionList">List of Reactions</li>
        </div>

        <div id="incomplete_reaction" class="alert alert-danger" role="alert" style="display:none">
          You must enter a Reaction Formula.
        </div>

        <div class="row col-lg-12" style="padding-top:20px;">
          <button type="button" class="btn btn-default ghost-btn" id="add_reaction">Add Reaction</button>
        </div>
        
        <div class="row col-lg-12">
          <label>Output Frequency:</label>
          <input type="text" class="form-control" id="output_frequency" placeholder="Output Frequency" aria-describedby="basic-addon1">
        </div>

        <div class="row col-lg-12">
          <label>Random Seed:</label>
          <input type="text" class="form-control" id="random_seed" placeholder="Random Seed" aria-describedby="basic-addon1">
        </div>

        <div id="incomplete_data" class="alert alert-danger" role="alert" style="display:none">
          You must enter have data for all fields.
        </div>

        <div class="row col-lg-12" align="center">
          <input type="submit" class="btn btn-default ghost-btn" id="run_sim" value="Run Simulation">
        </div>

        <div class="row">
          <ul class="list-group" id="listOfInputs">
              
              
              
          </ul>
        </div>

      </div>
    </div>
  </div>
  </form>
</div>


<script>
  var all_reagent_names = [];
  var all_reagent_concen = [];
  $("#add_reagent").click(function(){
      var reagent_name = $("#reagent").val();
      var reagent_concen = $("#reagent_concen").val();

      if (reagent_name == "" || reagent_concen == "") {
        $("#incomplete_reagent").attr("style", "display:block");
      }
      else {
        $("#incomplete_reagent").hide();
        all_reagent_names.push(reagent_name);
        all_reagent_concen.push(reagent_concen);
        $("#reagent").val("");
        $("#reagent_concen").val("");

        $("#reagentNamesList").text("[" + all_reagent_names + "]");
        $("#reagentConcenList").text("[" + all_reagent_concen + "]");
      }
  });

  var all_reactions = [];
  $("#add_reaction").click(function(){
      var reaction = $("#reaction").val();

      if (reaction == "") {
        $("#incomplete_reaction").attr("style", "display:block");
      }
      else {
        $("#incomplete_reaction").hide();
        all_reactions.push(reaction);
        $("#reaction").val("");

        $("#reactionList").text(all_reactions);
      }
  });

  $("#run_sim").click(function(){
      if (num_of_iterations == "" || output_frequency == "" || random_seed == "") {
        $("#incomplete_data").attr("style", "display:block");
      }
      else {
        $("#incomplete_reaction").hide();

        var link = document.getElementById('downloadlink');

        var num_of_iterations = $("#num_of_iterations").val();
        var data = "[Iterations]\n" + num_of_iterations

      }
  });

  var textFile = null,
  makeTextFile = function (text) {
    var data = new Blob([text], {type: 'text/plain'});

    // If we are replacing a previously generated file we need to
    // manually revoke the object URL to avoid memory leaks.
    if (textFile !== null) {
      window.URL.revokeObjectURL(textFile);
    }

    textFile = window.URL.createObjectURL(data);

    return textFile;
  };

  
  
</script>


<script>
  var count = 0;
  $("#addData").click(function(){

  alert("chris got no game");
    if (count === 0)
    {
      var text = $("#molecule").val();
      $("#moleculeList").text(text);

      var initconcen = $("#initConcen").val();
      alert(initconcen);
      initconcen = text.substring(0,3) + "-" + initconcen;
      $("#concentrations").text(initconcen);


      count ++;
    }
    else
    {
      var text = $("#moleculeList").text();   //variable gets text inside of mol. list
      var newText = $("#molecule").val();   //variable gets value of inputted concentration
      newText = newText.substring(0,3);       //cuts newText to only first 3 letters
      text = text + ", " + $("#molecule").val(); //creates total text value for mol. list
      $("#moleculeList").text(text);

      var initconcen = $("#concentrations").text();
      var x = parseInt($("#initConcen").text());
      initconcen = initconcen + ", " + newText + "-" + x;
      $("#concentrations").text(initconcen);


    }
  });
</script>

<style>
.row{
  padding: 10px;
}
#body{
  padding-top: 30px;
  padding-left: 15px;
  padding-right: 15px;
}
</style>

</div>
{% include 'common/_footer.html' %}

skeletonpages/templates/skeletonpages/instructions.html
{% include 'common/_header.html' %}

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="alert alert-info">
			This is what your instructions page looks like.  Your active tab is {{ active_tab }}.
		</div>
	</div>
</div>

{% include 'common/_footer.html' %}

skeletonpages/templates/skeletonpages/simulation_running.html
{% include "common/_header.html" %}



<div class="">
  <div class="row profile-detail-first-row">
    <div class="col-md-12 status-cols">
        <div class="my-profile" style="padding-top: 35px;">
          <div class="status text-center">
            SIMULATION SUBMITTED
          </div>
        </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <div class="submitted-text top-line">
      Thank you for using GAUSS.
    </div>
    <div class="submitted-text">
      Your simulation is now running.  Once you return to your profile, you will be able to see the status of your simulation at any time.
    </div>
    <div class="submitted-text" style="padding-bottom: 50px">
      Once your simulation is complete, simply click on its name to review the results.  You will be able to view several graphs of the output or, if you wish, download the full output file for your own analysis.
    </div>
  </div>
</div>





{% include "common/_footer.html" %}