pgss15compbio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from pgss15compbio import views


urlpatterns = [
    url(r'^$', views.hello, name="hello"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^skeletonpages/', include('skeletonpages.urls')),
    url(r'^accounts/', include('userena.urls')),
    # 'django.views.static.serve',
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skeletonpages/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.db.models.signals import post_save, post_init
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile
from time import strftime

class DemoObject(models.Model):
  object_name = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Object Name")
  object_description = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Object Description")
  object_number = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Object Number")

  def __unicode__(self):
    return "{}".format(self.object_name or self.object_description or "N/A")

def upload_path(self, filename):
  return strftime("%Y/%m/%d/%H/%M/{}".format(filename))

class AlgorithmRun(models.Model):
  # status should be "PROCESSING" or "COMPLETE"
  status = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Status")
  
  name = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Name")
  description = models.CharField(max_length = 2048, null = True, blank = True, verbose_name = "Description")
  input_file = models.FileField(upload_to = upload_path, null = True, blank = True)
  output_file = models.FileField(upload_to = upload_path, null = True, blank = True)
  input_text = models.CharField(max_length = 8192, null = True, blank = True, verbose_name = "Input Text")
  output_text = models.CharField(max_length = 32768, null = True, blank = True, verbose_name = "Output Text")
  def __unicode__(self):
    return "{}".format(self.name or "Unnamed Algorithm Run")


class UserProfile(UserenaBaseProfile):
  user = models.OneToOneField(User)

  algorithm_runs = models.ManyToManyField(AlgorithmRun, null = True, blank = True)

  organization = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Organization Name")
  scientific_field = models.CharField(max_length = 255, null = True, blank = True, verbose_name = "Field")

  def __unicode__(self):
      return "Profile information for {}".format(self.user.email)

  class Meta:
      verbose_name = "Profile"
      verbose_name_plural = "Profiles"

  def create_user_profile(sender, instance, created, **kwargs):
      if created:
          UserProfile.objects.create(user=instance)

templates/userena/profile_detail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load extras %}


{% block title %}GAUSS | SciReact{% endblock %}

{% block content %}
{% include "common/_header.html" %}

<div class="">

  <div class="row profile-detail-first-row">
    <div class="col-md-5 col-md-offset-1"  style="padding-bottom: 35px; color: white;">
      {% comment %}Dirty hack. Will use django-guardian in the future.{% endcomment %}
      {% if user.username == profile.user.username %}
        <div class="my-profile" style="padding-top: 35px;">My Profile</div>
        <div class="profile-group">
          <span class="profile-attribute">Name: </span>
          <span class="profile-attribute-value">{{ profile.user.get_full_name }}</span>
        </div>
        <div class="profile-group">
          <span class="profile-attribute">Email: </span>
          <span class="profile-attribute-value">{{ profile.user.email }}</span>
        </div>
        <div class="profile-group">
          <span class="profile-attribute">Organization: </span>
          <span class="profile-attribute-value">{{ profile.organization }}</span>
        </div>
        <div class="profile-group">
          <span class="profile-attribute">Fields: </span>
          <span class="profile-attribute-value">{{ profile.scientific_field }}</span>
        </div>
      {% endif %}

        <!-- <img class="mugshot" src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" /> -->
    </div>
  </div>
  <br>
  <div class="row" style="margin-left: 7.5%">
    <div class="col-md-5 col-md-offset-1">
        <div class="my-profile" style="padding-top: 15px;">
          My Simulations
        </div>
    </div>
  </div>
  <div class="row" style="margin-left: 7.5%">
    <div class="col-md-5 col-md-offset-1">
      <div class="text-left">
        <a href="/skeletonpages/simulations/new/">
          <button class="btn btn-default">
            New Simulation
          </button>
        </a>
      </div>
    </div>
  </div>
</div>
<br><br>

<div class="col-lg-10 col-lg-offset-1">
{% for run in profile.algorithm_runs.all %}
  {% ifequal forloop.counter0|modulo:3 0 %}
    <div class="row" style="margin-left: 7.5%; margin-right: 7.5%; padding-bottom: 35px">
  {% endifequal %}
    <div class="col-md-4">
      <div class="run-container">
        <div class="run-top-portion">
          <div class="run-name text-center">
            {% if run.status == "COMPLETE" %}
              <span class="glyphicon glyphicon-ok" class="run-name" style="position: relative; float: left; color: green; padding-left: 5px; font-size: 13px;" title="This simulation has completed processing"></span>
            {% else %}
              <span class="glyphicon glyphicon-refresh" class="run-name" style="position: relative; float: left; color: gray; padding-left: 5px; font-size: 13px;" title="This simulation is still processing.  Check back soon!"></span>
            {% endif %}

            {% if run.status == "COMPLETE" %}
              <a href="/skeletonpages/simulations/{{run.id}}/show/" class="run-name-link"> {{ run.name }}</a>
            {% else %}
              {{ run.name }}
            {% endif %}
            <a href="/skeletonpages/simulations/{{run.id}}/delete/" class="run-name" style="position:relative;float:right;color:red;padding-right:5px;font-size:13px"> X</a>
          </div>
        </div>
        <div class="run-bottom-portion">
          <div class="run-desc text-center">
            <br>
            {{ run.description }}
          </div>
        </div>
      </div>
    </div>

  {% if forloop.counter0|modulo:3 == 2 or forloop.last %}
    </div>
    <br>
  {% endif %}
{% endfor %}
</div>

<div class="row gauss-row">
  <div class="col-md-12">

  </div>
</div>

{% include "common/_footer.html" %}  

<script>

$(window).load(function(){
  h = $(".background-image").height();
  $(".black-overlay-2").height(h);
});

</script>


<style type="text/css">
  .profile-group{
    font-family: Roboto;
    font-size: 15px;
    padding: 5px;
  }

</style>

{% endblock %}

templates/userena/profile_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "GAUSS | SciReact" %}{% endblock %}
{% block content %}
{% include "common/_header.html" %}

<div class="row jumbotron">
  <div class="col-md-4 col-md-offset-4">
    <div class="center">
      <div style="padding-bottom: 15px;">
        <span class="larger-text" style="color:white;">
          <h1>Edit Profile</h1>
        </span>
        <!--
        <span class="text-right" style="float: right; margin-top: 19px">
          <a style="color:white;" href="{% url 'userena_password_change' user.username %}">
            Edit Password
          </a>
        </span>
        -->
      </div>
      <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <fieldset>
          <p class="form-box">
            <input placeholder="First name" class="required form-control-pad" id="id_first_name" maxlength="30" name="first_name" type="text" value="{{user.first_name}}"/>
          </p>
          <p class="form-box">
            <input placeholder="Last name" class="required form-control-pad" id="id_last_name" maxlength="30" name="last_name" type="text" value="{{user.last_name}}"/>
          </p>
          <p style="display: none;">
            <label for="id_mugshot">Mugshot:</label><input id="id_mugshot" name="mugshot" type="file"/><span class="helptext">A personal image displayed in your profile.</span>
          </p>
          <p style="display: none;">
            <label for="id_privacy">Privacy:</label>
            <select id="id_privacy" name="privacy">
              <option value="open">Open</option>
              <option value="registered" selected="selected">Registered</option>
              <option value="closed">Closed</option>
            </select>
            <span class="helptext">Designates who can view your profile.</span>
          </p>
          <p style="display: none">
            <select multiple="multiple" id="id_algorithm_runs" name="algorithm_runs">
              {% for run in profile.algorithm_runs.all %}
                <option value="{{ run.id }}" selected="selected">{{ run.name }}</option>
              {% endfor %}
            </select>
          </p>
          <p class="form-box">
            <input placeholder="Organization" class="required form-control-pad" id="id_organization" maxlength="255" name="organization" type="text" value="{{profile.organization}}"/>
          </p>
          <p class="form-box">
            <input placeholder="Scientific Field" class="required form-control-pad" id="id_scientific_field" maxlength="255" name="scientific_field" type="text" value="{{profile.scientific_field}}"/>
          </p>
        </fieldset>
        <div class="text-center">
          <button type="submit" class="btn btn-lg btn-primary">UPDATE</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% include "common/_footer.html" %}
{% endblock %}

templates/userena/signin_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "GAUSS | SciReact" %}{% endblock %}

{% block content %}


<!DOCTYPE html>
<html>
<head>
  <title>GAUSS | SciReact</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.4.js"></script>

</head>
<body data-spy='scroll'>

  <nav class="navbar navbar-default navbar-fixed-top navbar-height navbar-styled" id="homepage-navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle na.navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/accounts/signup" class="navbar-right-link">Register</a></li>
          <li><a href="/accounts/signin" class="navbar-right-link" style="opacity: 1">Log In</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="black-overlay">
  <img class="background-image" src="http://4.bp.blogspot.com/-ci8zjNrp50I/U_yCxyehuzI/AAAAAAAADX4/uiAIDRcpUB4/s1600/ahagzjsozh.jpg" />
  <div class="black-overlay-2"></div>
</div>
<div class="row home-jumbo-row">
    <div class="col-md-6 col-md-offset-3 signup-box">
        <form action method="post">
          {% csrf_token %}
          {{ form.non_field_errors }}
          {% for field in form %}
          {{ field.errors }}
          {% endfor %}
        <fieldset>
          <p class="form-box">
          <input placeholder="Username" class="required form-control" id="id_identification" maxlength="75" name="identification" type="text" />
          </p>
          <p class="form-box">
          <input placeholder="Password" class="required form-control" id="id_password" name="password" type="password" />
          </p>
          <p class="checkbox">
          <label for="id_remember_me" class="remember-me-checkbox"><input id="id_remember_me" name="remember_me" type="checkbox" class="remember-me-checkbox-input" /> <span class="rem">Remember me for a month</span></label>
          </p>
        </fieldset>
            <div class="text-center">
                <button type="submit" value="Signup" class="ghost-button">WELCOME BACK</button>
            </div>
        </form>
    </div>
</div>
<script>

$(window).load(function(){
  h = $(".background-image").height();
  $(".black-overlay-2").height(h);
});

</script>

</body>
</html>

<script>
  $(document).ready(function(){
    var is_transparent_now = true;

    $(window).scroll(function(){
      if( $(window).scrollTop() < 15 && !is_transparent_now){
        is_transparent_now = true;
        $(".navbar-right-link").animate({
          color: $.Color(255, 255, 255, 0.75)
        }, 500);
        $("#homepage-navbar").animate({
          backgroundColor: $.Color(255, 255, 255, 0)
        }, 500);
      }
      else if ( $(window).scrollTop() >= 15 && is_transparent_now )
      {
        is_transparent_now = false;
        $(".navbar-right-link").animate({
          color: $.Color(0, 0, 0, 0.7)
        }, 500);
        $("#homepage-navbar").animate({
          backgroundColor: $.Color(255, 255, 255, 0.95)
        }, 500);
      }
    })
  });
</script>


<style type="text/css">


  @import url(http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800);
  @import url(http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic);

.remember-me-checkbox{
  color: white;
}

.remember-me-checkbox-input{
  width: 25px;
  height: 25px;
}

.rem{
  padding-left: 15px;
  font-size: 23px;
  font-weight: 100;
  font-family: "Roboto", sans-serif;
}

.form-box{
    padding-bottom: 6px;
}
.ghost-button{
    color: white;
    font-size: 30px;
    border-style: none;
    background-color: transparent;
    border: 6px solid white;
    margin-top: 30px;
    padding: 14px 41px;
    font-weight: bolder;
    font-family: "Open Sans", sans-serif;
}

.description{
  color: white;
  font-family: "Roboto", sans-serif;
  font-weight: 100;
  font-size: 23px;
  padding-top: 45px;
}

.form-control{
    border-radius: 0px;
    height: 50px;
    font-size: 24px;
    font-weight: 100;
    font-family: "Roboto", sans-serif;
}

.signup-box{
    background-color: rgba(255, 255, 255, 0);
    padding: 30px 50px;
    border: 5px solid rgba(2, 69, 0, 0);
}

.navbar-height {
  z-index: 1000;
}

.navbar-white-trans {
  background-color: black !important;
}

.black-link {
  color: rgba(0, 0, 0, 0.76) !important;
}

.navbar-styled {
  right: 0;
  width: 100%;
  background-color: transparent;
  border: none;
  margin-bottom: 0px;
  border-radius: 0px;
}

.navbar-styled .navbar-nav li a {
  float: left;
  font-family: "Open Sans", sans-serif;
  font-size: 19px;
  opacity: 0.75;
  color: white;
  -webkit-transition: opacity 250ms ease-in-out;
  -moz-transition: opacity 250ms ease-in-out;
  -o-transition: opacity 250ms ease-in-out;
  transition: opacity 250ms ease-in-out;
}

.navbar-styled .navbar-nav li a:hover {
  color: white;
  opacity: 1;
}

.navbar-styled .navbar-nav li .link-for-light-background {
  color: #5a5a5a;
  opacity: 0.6;
  -webkit-transition: opacity 250ms ease-in-out;
  -moz-transition: opacity 250ms ease-in-out;
  -o-transition: opacity 250ms ease-in-out;
  transition: opacity 250ms ease-in-out;
}

.navbar-styled .navbar-nav li .link-for-light-background:hover {
  color: #5a5a5a;
  opacity: 1;
}

.navbar-styled .navbar-header .navbar-brand {
  color: white;
}

.navbar-styled .navbar-header .foundation-brand {
  font-family: "Open Sans",sans-serif;
  font-size: 40px;
  font-weight: 600;
  color: white;
  opacity: 0.7;
}

.background-image {
  width: 100%;
  height: auto;
}

.black-overlay {
  background-color: black;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: auto;
}

.black-overlay-2 {
  background-color: rgba(0, 0, 0, 0.2);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: auto;
}

.home-jumbo-row {
  margin-left: 6.5%;
  margin-right: 6.5%;
  padding-top: 8.2%;
}

.home-jumbo-row .home-page-right-side-column {
  padding-left: 5%;
}

.home-jumbo-row .home-page-right-side {
  padding-top: 3.5%;
}

.home-jumbo-row .most-rigorous {
  background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.18), transparent);
  color: white;
  padding: 50px;
  text-align: center;
  font-size: 25px;
  line-height: 33px;
  font-family: "Roboto";
  font-weight: 100;
}

.sci-react-home-title {
  color: white;
  font-size: 156px;
  font-family: "Open Sans", sans-serif;
  line-height: 68px;
  font-weight: bold;
  letter-spacing: 60px;
}

/* For lines around text */
.double-lined-text {
  line-height: 0.2;
  text-align: center;
}

.double-lined-text span {
  display: inline-block;
  position: relative;
  font-family: "Roboto";
  font-size: 33px;
  font-weight: 100;
}

.double-lined-text span:before,
.double-lined-text span:after {
  content: "";
  position: absolute;
  height: 5px;
  border-bottom: 1px solid white;
  border-top: 1px solid white;
  top: 0;
  width: 150%;
}

.double-lined-text span:before {
  right: 100%;
  margin-right: 15px;
}

.double-lined-text span:after {
  left: 100%;
  margin-left: 15px;
}

</style>

{% endblock %}

templates/userena/signout.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "GAUSS | SciReact" %}{% endblock %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
  <title>GAUSS | SciReact </title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.4.js"></script>

</head>
<body data-spy='scroll'>

  <nav class="navbar navbar-default navbar-fixed-top navbar-height navbar-styled" id="homepage-navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle na.navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/accounts/signup" class="navbar-right-link">Register</a></li>
          <li><a href="/accounts/signin" class="navbar-right-link">Log In</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="black-overlay">
  <img class="background-image" src="../../static/material_background.jpg" />
  <div class="black-overlay-2"></div>
</div>
<div class="row home-jumbo-row">
  <div class="col-md-12 sci-react-home-title-columns text-center"><br /><br />
    <div class="sci-react-home-title-small">SIGNED OUT</div>
    <div class="description">Thank you for visiting SciReact.</div>
  </div>
</div>
<script>

$(window).load(function(){
  h = $(".background-image").height();
  $(".black-overlay-2").height(h);
});

</script>

</body>
</html>

<script>
  $(document).ready(function(){
    var is_transparent_now = true;

    $(window).scroll(function(){
      if( $(window).scrollTop() < 15 && !is_transparent_now){
        is_transparent_now = true;
        $(".navbar-right-link").animate({
          color: $.Color(255, 255, 255, 0.75)
        }, 500);
        $("#homepage-navbar").animate({
          backgroundColor: $.Color(255, 255, 255, 0)
        }, 500);
      }
      else if ( $(window).scrollTop() >= 15 && is_transparent_now )
      {
        is_transparent_now = false;
        $(".navbar-right-link").animate({
          color: $.Color(0, 0, 0, 0.7)
        }, 500);
        $("#homepage-navbar").animate({
          backgroundColor: $.Color(255, 255, 255, 0.95)
        }, 500);
      }
    })
  });
</script>


<style type="text/css">

  @import url(http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800);
  @import url(http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic);

.description{
  color: white;
  font-family: "Roboto", sans-serif;
  font-weight: 100;
  font-size: 23px;
  padding-top: 45px;
}

.navbar-height {
  z-index: 1000;
}

.navbar-white-trans {
  background-color: black !important;
}

.black-link {
  color: rgba(0, 0, 0, 0.76) !important;
}

.navbar-styled {
  right: 0;
  width: 100%;
  background-color: transparent;
  border: none;
  margin-bottom: 0px;
  border-radius: 0px;
}

.navbar-styled .navbar-nav li a {
  float: left;
  font-family: "Open Sans", sans-serif;
  font-size: 19px;
  opacity: 0.75;
  color: white;
  -webkit-transition: opacity 250ms ease-in-out;
  -moz-transition: opacity 250ms ease-in-out;
  -o-transition: opacity 250ms ease-in-out;
  transition: opacity 250ms ease-in-out;
}

.navbar-styled .navbar-nav li a:hover {
  color: white;
  opacity: 1;
}

.navbar-styled .navbar-nav li .link-for-light-background {
  color: #5a5a5a;
  opacity: 0.6;
  -webkit-transition: opacity 250ms ease-in-out;
  -moz-transition: opacity 250ms ease-in-out;
  -o-transition: opacity 250ms ease-in-out;
  transition: opacity 250ms ease-in-out;
}

.navbar-styled .navbar-nav li .link-for-light-background:hover {
  color: #5a5a5a;
  opacity: 1;
}

.navbar-styled .navbar-header .navbar-brand {
  color: white;
}

.navbar-styled .navbar-header .foundation-brand {
  font-family: "Open Sans",sans-serif;
  font-size: 40px;
  font-weight: 600;
  color: white;
  opacity: 0.7;
}

.background-image {
  width: 100%;
  height: auto;
}

.black-overlay {
  background-color: black;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: auto;
}

.black-overlay-2 {
  background-color: rgba(0, 0, 0, 0.2);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: auto;
}

.home-jumbo-row {
  margin-left: 6.5%;
  margin-right: 6.5%;
  padding-top: 8.2%;
}

.home-jumbo-row .home-page-right-side-column {
  padding-left: 5%;
}

.home-jumbo-row .home-page-right-side {
  padding-top: 3.5%;
}

.home-jumbo-row .most-rigorous {
  background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.18), transparent);
  color: white;
  padding: 50px;
  text-align: center;
  font-size: 25px;
  line-height: 33px;
  font-family: "Roboto";
  font-weight: 100;
}

.sci-react-home-title {
  color: white;
  font-size: 156px;
  font-family: "Open Sans", sans-serif;
  line-height: 68px;
  font-weight: bold;
  letter-spacing: 60px;
}

.sci-react-home-title-small {
  color: white;
  font-size: 100px;
  font-family: "Open Sans", sans-serif;
  line-height: 68px;
  font-weight: bold;
  /*letter-spacing: 60px;*/
}

/* For lines around text */
.double-lined-text {
  line-height: 0.2;
  text-align: center;
}

.double-lined-text span {
  display: inline-block;
  position: relative;
  font-family: "Roboto";
  font-size: 33px;
  font-weight: 100;
}

.double-lined-text span:before,
.double-lined-text span:after {
  content: "";
  position: absolute;
  height: 5px;
  border-bottom: 1px solid white;
  border-top: 1px solid white;
  top: 0;
  width: 150%;
}

.double-lined-text span:before {
  right: 100%;
  margin-right: 15px;
}

.double-lined-text span:after {
  left: 100%;
  margin-left: 15px;
}



</style>


{% endblock %}